#!/usr/bin/env bash
# Build the installable marketplace for both hosts into an empty directory outside this checkout.
# The release workflow publishes this layout to the `dist` branch.
set -euo pipefail
cd "$(dirname "$0")/.."
out="${1:?usage: integrations/package.sh <empty-directory-outside-the-checkout>}"
mkdir -p "$out"
[ -z "$(ls -A "$out" | grep -vx .git || true)" ] || { echo "package: $out is not empty" >&2; exit 2; }
out="$(cd "$out" && pwd)"
version=$(jq -r .version plugins/o-harness/.claude-plugin/plugin.json)
[ "$version" = "$(jq -r .version plugins/o-harness/.codex-plugin/plugin.json)" ] || {
  echo "package: the Claude and Codex plugin versions differ" >&2; exit 2; }

./oh build-plugin "$out/claude/o-harness" --host claude >/dev/null
./oh build-plugin "$out/codex/o-harness" --host codex >/dev/null
mkdir -p "$out/.claude-plugin" "$out/.agents/plugins"
cat > "$out/.claude-plugin/marketplace.json" <<'JSON'
{
  "name": "o-harness",
  "owner": {"name": "OH contributors"},
  "description": "OH: explicit, independently reviewed agent workflows.",
  "plugins": [{"name": "o-harness", "source": "./claude/o-harness",
    "description": "Explicit, independently reviewed workflows with external state and subscription workers."}]
}
JSON
cat > "$out/.agents/plugins/marketplace.json" <<'JSON'
{
  "name": "o-harness",
  "interface": {"displayName": "OH"},
  "plugins": [{"name": "o-harness", "source": {"source": "local", "path": "./codex/o-harness"},
    "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"}, "category": "Productivity"}]
}
JSON
cat > "$out/README.md" <<EOF
# o-harness $version (built packages)

Generated by the release workflow. Do not edit this branch.
Source and installation guide: https://github.com/pmoreiracc/o-harness
EOF
echo "$out"
